<a href="https://colab.research.google.com/github/sasiphatcha/PythonDataViz2026/blob/main/hw5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW5 673020639-5

## เขียน function คูณ matrix แล้ว test กับ matrix ขนาด
(2,3)* (3,2)
,
(4,4)* (4,1)
,
(2,2)* (2,2)

In [ ]:
import numpy as np
def matric_multi(A, B):
    m = len(A)
    a = len(A[0])
    b = len(B)
    n = len(B[0])
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            for sum in range(a):
                C[i, j] = C[i, j] + A[i, sum] * B[sum, j]
    return C

In [ ]:
A1 = np.array([[1, 2, 3], [4, 5, 6]])
B1 = np.array([[7, 8], [9, 1], [2, 3]])

print("--- ผลลัพธ์ (2,3) * (3,2) ---")
print(matric_multi(A1, B1))
print()

--- ผลลัพธ์ (2,3) * (3,2) ---
[[31. 19.]
 [85. 55.]]



In [ ]:
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3], [4, 5, 6, 7]])
B2 = np.array([[1], [2], [3], [4]])

print("--- ผลลัพธ์ (4,4) * (4,1) ---")
print(matric_multi(A2, B2))
print()

--- ผลลัพธ์ (4,4) * (4,1) ---
[[30.]
 [70.]
 [29.]
 [60.]]



In [ ]:
A3 = np.array([[1, 2], [3, 4]])
B3 = np.array([[5, 6], [7, 8]])

print("--- ผลลัพธ์ (2,2) * (2,2) ---")
print(matric_multi(A3, B3))

--- ผลลัพธ์ (2,2) * (2,2) ---
[[19. 22.]
 [43. 50.]]
